version: 1.54.2
run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - gosimple
    - staticcheck
    - unused
    - gofumpt
    - goimports
    - revive


